/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 atm.glb 
Author: abdillaamy (https://sketchfab.com/abdillaamy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/high-detailed-automatic-teller-machine-atm-83a8dde1ae4546cf9a0e68d6e7b6947a
Title: High Detailed Automatic Teller Machine (ATM)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Atm(props) {
  const { nodes, materials } = useGLTF('/resources/atm.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.198, 731.018, 0]} scale={[437.512, 1451.091, 351.871]}>
        <mesh geometry={nodes.ATM_HighRes2_GreyPlastic_0.geometry} material={materials.GreyPlastic} />
        <mesh geometry={nodes.ATM_HighRes2_Bronze_0.geometry} material={materials.Bronze} />
        <mesh geometry={nodes.ATM_HighRes2_BluePlastic_0.geometry} material={materials.BluePlastic} />
        <mesh geometry={nodes.ATM_HighRes2_Screen_0.geometry} material={materials.Screen} />
        <mesh geometry={nodes.ATM_HighRes2_Keys_0.geometry} material={materials.Keys} />
        <mesh geometry={nodes.ATM_HighRes2_Camera_0.geometry} material={materials.Camera} />
      </group>
    </group>
  )
}

export default Atm
useGLTF.preload('/resources/atm.glb')
