/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 boy.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Boy(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/resources/boy.glb')
  const { actions, mixer } = useAnimations(animations, group)

  useEffect(() => {
    
    const action = props.action.currentAction;
    mixer.stopAllAction();

    if (action === 'forward' || action ==='backward' || action ==='leftward'|| action==='rightward' || action==='run') {
      actions.walking.reset().play();
    } 
    else{
      actions.idle.reset().play();
    }
  }, [props.action.currentAction, actions, mixer]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="body" geometry={nodes.body.geometry} material={materials['Material.015']} skeleton={nodes.body.skeleton} />
          <skinnedMesh name="groin" geometry={nodes.groin.geometry} material={materials['Material.002']} skeleton={nodes.groin.skeleton} />
          <skinnedMesh name="hair" geometry={nodes.hair.geometry} material={materials['Material.004']} skeleton={nodes.hair.skeleton} />
          <skinnedMesh name="head" geometry={nodes.head.geometry} material={materials['Material.005']} skeleton={nodes.head.skeleton} />
          <skinnedMesh name="left" geometry={nodes.left.geometry} material={materials['Material.017']} skeleton={nodes.left.skeleton} />
          <skinnedMesh name="left_center" geometry={nodes.left_center.geometry} material={materials['Material.001']} skeleton={nodes.left_center.skeleton} />
          <skinnedMesh name="left_leg" geometry={nodes.left_leg.geometry} material={materials['Material.002']} skeleton={nodes.left_leg.skeleton} />
          <skinnedMesh name="neck" geometry={nodes.neck.geometry} material={materials['Material.007']} skeleton={nodes.neck.skeleton} />
          <skinnedMesh name="right" geometry={nodes.right.geometry} material={materials['Material.017']} skeleton={nodes.right.skeleton} />
          <skinnedMesh name="right_center" geometry={nodes.right_center.geometry} material={materials['Material.001']} skeleton={nodes.right_center.skeleton} />
          <skinnedMesh name="shirt" geometry={nodes.shirt.geometry} material={materials['Material.006']} skeleton={nodes.shirt.skeleton} />
          <skinnedMesh name="shoe_left" geometry={nodes.shoe_left.geometry} material={materials['Material.003']} skeleton={nodes.shoe_left.skeleton} />
          <skinnedMesh name="실린더" geometry={nodes.실린더.geometry} material={materials['Material.009']} skeleton={nodes.실린더.skeleton} />
        </group>
      </group>
    </group>
  )
}
export default Boy;
useGLTF.preload('/resources/boy.glb')
