/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cabinet.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cabinet(props) {
  const { nodes, materials } = useGLTF('/resources/cabinet.glb')
  return (
    <>
    <pointLight
      args={['gold', 2,2,1]}
      position={[5.3,6,1]}
      rotation-x={Math.PI/2}
    />
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.BookAAAAAAB9} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.BookAAAAAAC7} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.BookAAAAAAC8} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.BookAAAAAAC9} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.BookAAAAAAC99} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.BookAAAAAA4} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.BookAAAAAA66} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.BookAAAAAAC343243} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.BookAAAAAAB3} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.BookAAAAAA5} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.BookAAAAAAC1} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.BookAAAAAAC2} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.BookAAAAAAC3} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.BookAAAAAAC4} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.BookAAAAAA1} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.BookAAAAAA2} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.BookAAAAAA7} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.BookAAAAAA8} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.BookAAAAAA9} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.BookAAAAAAB1} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.BookAAAAAAB4} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.BookAAAAAAB5} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.BookAAAAAAB6} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.BookAAAAAAB7} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.BookAAAAAAB8} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.BookAAAAAAB2} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.BookAAAAAAC5} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.BookAAAAAAC6} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.BookAAAAAA3} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_64.geometry} material={materials['BookAAAAAAC23341455.001']} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['BookAAAAAAC283823873.001']} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
    </group>
    </>
  )
}
export default Cabinet
useGLTF.preload('/resources/cabinet.glb')
