/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 carpet.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Carpet(props) {
  const { nodes, materials } = useGLTF('/resources/carpet.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.2, 0, -4]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Carpet_01} />
        <mesh geometry={nodes.Object_8001.geometry} material={materials.Carpet_01} position={[1.898, 0, 0]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      </group>
      <group position={[1.2, 0, -4]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_12.geometry} material={materials.Carpet_01} position={[-1.44, 0, 0]} />
      </group>
    </group>
  )
}
export default Carpet;
useGLTF.preload('/resources/carpet.glb')
