/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 chandelier.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chandelier(props) {
  const { nodes, materials } = useGLTF('/resources/chandelier.glb')
  return (
    <>
    <pointLight
      args={['white', 300,10,5]}
      position={[2,9,1]}
      rotation-z={Math.PI/2}
    />
    
    <group {...props} dispose={null}>
      <group position={[-0.006, -115.255, -1.13]}>
        <mesh geometry={nodes.Box001_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.006, -137.542, -1.13]}>
        <mesh geometry={nodes.Box002_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.002, -147.548, -1.068]}>
        <mesh geometry={nodes.Box003_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.002, -126.406, -1.068]}>
        <mesh geometry={nodes.Box004_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.002, -105.263, -1.068]}>
        <mesh geometry={nodes.Box005_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.423, -173.527, -0.082]}>
        <mesh geometry={nodes.Box006_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[78.247, -37.247, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box092_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[122.711, 113.939, -0.586]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box093_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[122.703, 82.509, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box094_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[150.089, -100.143, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box095_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[150.089, -79.001, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box096_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[150.097, -90.137, -0.586]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box097_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[150.089, -57.859, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box098_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[122.703, 103.651, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box099_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[150.097, -67.85, -0.586]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box100_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[249.197, -29.909, -0.526]} rotation={[Math.PI, -1.431, Math.PI]}>
        <mesh geometry={nodes.Box101_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[249.197, -51.051, -0.526]} rotation={[Math.PI, -1.431, Math.PI]}>
        <mesh geometry={nodes.Box102_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[249.197, -8.766, -0.526]} rotation={[Math.PI, -1.431, Math.PI]}>
        <mesh geometry={nodes.Box103_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[122.711, 92.515, -0.586]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box104_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[249.26, -18.758, -0.526]} rotation={[Math.PI, -1.431, Math.PI]}>
        <mesh geometry={nodes.Box105_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[249.26, -41.045, -0.526]} rotation={[Math.PI, -1.431, Math.PI]}>
        <mesh geometry={nodes.Box106_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[78.247, -101.705, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box107_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[78.255, -112.842, -0.586]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box108_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[78.247, -122.847, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box109_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[245.726, -8.659, -0.802]} rotation={[1.556, 0, 3.141]}>
        <mesh geometry={nodes.Box110_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.66, 19.841, -48.296]} />
      </group>
      <group position={[78.255, -90.555, -0.586]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box111_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[78.247, -80.563, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box112_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[122.703, 125.075, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box113_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[78.255, -47.239, -0.586]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box114_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[78.247, -58.389, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box115_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[78.255, -69.526, -0.586]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box116_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[78.255, -26.49, -0.586]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box117_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[78.247, -16.498, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box118_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[99.155, 169.317, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box119_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[99.163, 179.322, -0.586]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box120_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[99.155, 190.459, -0.649]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box121_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[99.579, 148.199, -1.625]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box122_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[78.672, -148.827, -1.634]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box123_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[249.552, -77.03, -1.634]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box124_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[123.127, 61.391, -1.625]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box125_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[150.514, -126.122, -1.634]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Box126_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[104.679, 51.867, 105.495]} rotation={[-Math.PI, 0.436, -Math.PI]}>
        <mesh geometry={nodes.Box173_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[104.66, 40.73, 105.555]} rotation={[-Math.PI, 0.436, -Math.PI]}>
        <mesh geometry={nodes.Box174_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[104.679, 30.725, 105.495]} rotation={[-Math.PI, 0.436, -Math.PI]}>
        <mesh geometry={nodes.Box175_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[105.476, 9.607, 104.789]} rotation={[-Math.PI, 0.436, -Math.PI]}>
        <mesh geometry={nodes.Box176_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[137.729, -94.488, 135.871]} rotation={[-Math.PI, 0.436, -Math.PI]}>
        <mesh geometry={nodes.Box177_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[136.927, -47.366, 136.584]} rotation={[-Math.PI, 0.436, -Math.PI]}>
        <mesh geometry={nodes.Box178_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[136.908, -58.502, 136.645]} rotation={[-Math.PI, 0.436, -Math.PI]}>
        <mesh geometry={nodes.Box179_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[136.927, -26.224, 136.584]} rotation={[-Math.PI, 0.436, -Math.PI]}>
        <mesh geometry={nodes.Box180_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[136.908, -36.215, 136.645]} rotation={[-Math.PI, 0.436, -Math.PI]}>
        <mesh geometry={nodes.Box181_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[136.927, -68.508, 136.584]} rotation={[-Math.PI, 0.436, -Math.PI]}>
        <mesh geometry={nodes.Box182_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[136.844, -20.08, 136.725]} rotation={[Math.PI, 0.698, 2.618]}>
        <mesh geometry={nodes.Box183_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.66, 19.841, -48.296]} />
      </group>
      <group position={[57.083, -37.247, 58.325]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box219_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[57.083, -101.705, 58.325]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box220_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[57.083, -58.389, 58.325]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box221_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[57.083, -122.847, 58.325]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box222_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[57.083, -80.563, 58.325]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box223_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[57.083, -16.498, 58.325]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box224_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[57.059, -112.842, 58.384]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box225_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[57.059, -69.526, 58.384]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box226_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[57.059, -26.49, 58.384]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box227_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[57.059, -47.239, 58.384]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box228_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[57.059, -90.555, 58.384]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box229_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[57.944, -148.827, 57.684]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.Box230_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[104.789, 9.724, -105.476]} rotation={[Math.PI, -1.134, Math.PI]}>
        <mesh geometry={nodes.Box231_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[-0.649, -100.143, -150.089]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box232_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.649, -79.001, -150.089]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box233_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.586, -90.137, -150.097]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box234_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.649, -57.859, -150.089]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box235_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.586, -67.85, -150.097]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box236_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[58.384, -47.239, -57.059]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box237_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[58.384, -26.49, -57.059]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box238_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[58.384, -69.526, -57.059]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box239_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[58.384, -112.842, -57.059]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box240_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[58.325, -16.498, -57.083]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box241_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[58.325, -80.563, -57.083]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box242_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[58.325, -122.847, -57.083]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box243_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[58.325, -58.389, -57.083]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box244_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[58.325, -101.705, -57.083]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box245_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[58.325, -37.247, -57.083]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box246_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[136.725, -20.08, -136.844]} rotation={[Math.PI, -0.873, 2.618]}>
        <mesh geometry={nodes.Box247_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.661, 19.841, -48.296]} />
      </group>
      <group position={[136.584, -68.508, -136.927]} rotation={[Math.PI, -1.134, Math.PI]}>
        <mesh geometry={nodes.Box248_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[136.644, -36.215, -136.908]} rotation={[Math.PI, -1.134, Math.PI]}>
        <mesh geometry={nodes.Box249_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-1.634, -126.122, -150.514]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box250_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[136.584, -26.224, -136.927]} rotation={[Math.PI, -1.134, Math.PI]}>
        <mesh geometry={nodes.Box251_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[105.495, 51.984, -104.679]} rotation={[Math.PI, -1.134, Math.PI]}>
        <mesh geometry={nodes.Box252_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[105.555, 40.848, -104.66]} rotation={[Math.PI, -1.134, Math.PI]}>
        <mesh geometry={nodes.Box253_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[105.495, 30.842, -104.679]} rotation={[Math.PI, -1.134, Math.PI]}>
        <mesh geometry={nodes.Box254_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[58.384, -90.555, -57.059]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box255_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[136.644, -58.502, -136.908]} rotation={[Math.PI, -1.134, Math.PI]}>
        <mesh geometry={nodes.Box256_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[136.584, -47.366, -136.927]} rotation={[Math.PI, -1.134, Math.PI]}>
        <mesh geometry={nodes.Box257_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[135.871, -94.488, -137.729]} rotation={[Math.PI, -1.134, Math.PI]}>
        <mesh geometry={nodes.Box258_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[-1.625, 61.391, -123.127]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box259_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[-1.634, -77.03, -249.552]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box260_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[-1.634, -148.827, -78.672]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box261_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[-0.649, -16.498, -78.246]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box262_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.586, -26.489, -78.255]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box263_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.586, -69.526, -78.255]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box264_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.649, -58.389, -78.246]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box265_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.586, -47.239, -78.255]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box266_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.649, -80.563, -78.246]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box267_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.586, -90.555, -78.255]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box268_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.649, -122.847, -78.246]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box269_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.586, -112.842, -78.255]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box270_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.649, -101.705, -78.246]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box271_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.649, -37.247, -78.246]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box272_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[57.685, -148.827, -57.944]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Box273_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[-0.526, -41.045, -249.26]} rotation={[0, -0.14, 0]}>
        <mesh geometry={nodes.Box274_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.526, -29.908, -249.197]} rotation={[0, -0.14, 0]}>
        <mesh geometry={nodes.Box275_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.526, -51.051, -249.197]} rotation={[0, -0.14, 0]}>
        <mesh geometry={nodes.Box276_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.526, -8.766, -249.197]} rotation={[0, -0.14, 0]}>
        <mesh geometry={nodes.Box277_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.802, -6.312, -245.429]} rotation={[Math.PI / 2, 0.015, 1.57]}>
        <mesh geometry={nodes.Box278_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.661, 19.841, -48.296]} />
      </group>
      <group position={[-0.526, -18.758, -249.26]} rotation={[0, -0.14, 0]}>
        <mesh geometry={nodes.Box279_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.649, 125.075, -122.703]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box280_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-1.625, 148.03, -99.579]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box281_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[-0.649, 103.651, -122.703]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box282_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.649, 82.509, -122.703]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box283_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.586, 113.939, -122.711]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box284_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.586, 92.515, -122.711]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box285_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.586, 179.153, -99.163]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box286_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-0.649, 190.29, -99.155]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box287_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-0.649, 168.978, -99.155]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Box288_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.776, -48.296]} />
      </group>
      <group position={[-105.476, 9.709, -104.789]} rotation={[0, -0.436, 0]}>
        <mesh geometry={nodes.Box289_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[-150.089, -100.143, 0.649]}>
        <mesh geometry={nodes.Box290_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-150.089, -79.001, 0.649]}>
        <mesh geometry={nodes.Box291_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-150.097, -90.137, 0.586]}>
        <mesh geometry={nodes.Box292_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-150.089, -57.859, 0.649]}>
        <mesh geometry={nodes.Box293_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-150.097, -67.85, 0.586]}>
        <mesh geometry={nodes.Box294_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-57.059, -47.239, -58.384]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box295_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-57.059, -26.489, -58.384]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box296_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-57.059, -69.526, -58.384]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box297_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-57.059, -112.842, -58.384]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box298_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-57.083, -16.498, -58.325]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box299_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-57.083, -80.563, -58.325]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box300_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-57.083, -122.847, -58.325]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box301_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-57.083, -58.389, -58.325]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box302_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-57.083, -101.705, -58.325]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box303_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-57.083, -37.247, -58.325]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box304_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-136.844, -20.08, -136.725]} rotation={[0, -0.698, -Math.PI / 6]}>
        <mesh geometry={nodes.Box305_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.66, 19.841, -48.296]} />
      </group>
      <group position={[-136.927, -68.508, -136.584]} rotation={[0, -0.436, 0]}>
        <mesh geometry={nodes.Box306_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-136.908, -36.215, -136.645]} rotation={[0, -0.436, 0]}>
        <mesh geometry={nodes.Box307_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-150.514, -126.122, 1.634]}>
        <mesh geometry={nodes.Box308_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[-136.927, -26.224, -136.584]} rotation={[0, -0.436, 0]}>
        <mesh geometry={nodes.Box309_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-104.679, 51.969, -105.495]} rotation={[0, -0.436, 0]}>
        <mesh geometry={nodes.Box310_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-104.66, 40.833, -105.555]} rotation={[0, -0.436, 0]}>
        <mesh geometry={nodes.Box311_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-104.679, 30.827, -105.495]} rotation={[0, -0.436, 0]}>
        <mesh geometry={nodes.Box312_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-57.059, -90.555, -58.384]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box313_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-136.908, -58.502, -136.645]} rotation={[0, -0.436, 0]}>
        <mesh geometry={nodes.Box314_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-136.927, -47.366, -136.584]} rotation={[0, -0.436, 0]}>
        <mesh geometry={nodes.Box315_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-137.729, -94.488, -135.871]} rotation={[0, -0.436, 0]}>
        <mesh geometry={nodes.Box316_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[-123.127, 61.391, 1.625]}>
        <mesh geometry={nodes.Box317_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[-249.552, -77.03, 1.634]}>
        <mesh geometry={nodes.Box318_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[-78.672, -148.827, 1.634]}>
        <mesh geometry={nodes.Box319_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[-78.247, -16.498, 0.649]}>
        <mesh geometry={nodes.Box320_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-78.255, -26.49, 0.586]}>
        <mesh geometry={nodes.Box321_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-78.255, -69.526, 0.586]}>
        <mesh geometry={nodes.Box322_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-78.247, -58.389, 0.649]}>
        <mesh geometry={nodes.Box323_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-78.255, -47.239, 0.586]}>
        <mesh geometry={nodes.Box324_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-78.246, -80.563, 0.649]}>
        <mesh geometry={nodes.Box325_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-78.255, -90.555, 0.586]}>
        <mesh geometry={nodes.Box326_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-78.246, -122.847, 0.649]}>
        <mesh geometry={nodes.Box327_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-78.255, -112.842, 0.586]}>
        <mesh geometry={nodes.Box328_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-78.246, -101.705, 0.649]}>
        <mesh geometry={nodes.Box329_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-78.247, -37.247, 0.649]}>
        <mesh geometry={nodes.Box330_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-57.944, -148.827, -57.684]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Box331_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[-249.26, -41.045, 0.526]} rotation={[0, 1.431, 0]}>
        <mesh geometry={nodes.Box332_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-249.197, -29.909, 0.526]} rotation={[0, 1.431, 0]}>
        <mesh geometry={nodes.Box333_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-249.197, -51.051, 0.526]} rotation={[0, 1.431, 0]}>
        <mesh geometry={nodes.Box334_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-249.197, -8.766, 0.526]} rotation={[0, 1.431, 0]}>
        <mesh geometry={nodes.Box335_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-245.43, -6.312, 0.802]} rotation={[1.586, 0, 0]}>
        <mesh geometry={nodes.Box336_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.66, 19.841, -48.296]} />
      </group>
      <group position={[-249.26, -18.758, 0.526]} rotation={[0, 1.431, 0]}>
        <mesh geometry={nodes.Box337_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-122.703, 124.394, 0.649]}>
        <mesh geometry={nodes.Box338_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-99.579, 148.526, 1.625]}>
        <mesh geometry={nodes.Box339_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[-122.703, 103.651, 0.649]}>
        <mesh geometry={nodes.Box340_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-122.703, 82.509, 0.649]}>
        <mesh geometry={nodes.Box341_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-122.711, 113.939, 0.586]}>
        <mesh geometry={nodes.Box342_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-122.711, 92.515, 0.586]}>
        <mesh geometry={nodes.Box343_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-99.163, 179.649, 0.586]}>
        <mesh geometry={nodes.Box344_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-99.155, 190.786, 0.649]}>
        <mesh geometry={nodes.Box345_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-99.155, 169.644, 0.649]}>
        <mesh geometry={nodes.Box346_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-104.79, 9.537, 105.476]} rotation={[0, 1.134, 0]}>
        <mesh geometry={nodes.Box347_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[0.649, -100.143, 150.089]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box348_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.649, -79.001, 150.089]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box349_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.586, -90.137, 150.097]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box350_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.649, -57.859, 150.089]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box351_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.586, -67.85, 150.097]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box352_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-58.384, -47.239, 57.059]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box353_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-58.384, -26.49, 57.059]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box354_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-58.384, -69.526, 57.059]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box355_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-58.384, -112.842, 57.059]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box356_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-58.325, -16.498, 57.083]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box357_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-58.325, -80.563, 57.083]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box358_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-58.325, -122.847, 57.083]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box359_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-58.325, -58.389, 57.083]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box360_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-58.325, -101.705, 57.083]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box361_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-58.325, -37.247, 57.083]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box362_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-136.725, -20.08, 136.844]} rotation={[0, 0.873, -Math.PI / 6]}>
        <mesh geometry={nodes.Box363_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.66, 19.841, -48.296]} />
      </group>
      <group position={[-136.584, -68.508, 136.927]} rotation={[0, 1.134, 0]}>
        <mesh geometry={nodes.Box364_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-136.645, -36.215, 136.908]} rotation={[0, 1.134, 0]}>
        <mesh geometry={nodes.Box365_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[1.634, -126.122, 150.514]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box366_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[-136.584, -26.224, 136.927]} rotation={[0, 1.134, 0]}>
        <mesh geometry={nodes.Box367_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-105.495, 51.797, 104.679]} rotation={[0, 1.134, 0]}>
        <mesh geometry={nodes.Box368_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-105.555, 40.661, 104.66]} rotation={[0, 1.134, 0]}>
        <mesh geometry={nodes.Box369_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-105.495, 30.655, 104.679]} rotation={[0, 1.134, 0]}>
        <mesh geometry={nodes.Box370_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-58.384, -90.555, 57.059]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box371_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-136.645, -58.502, 136.908]} rotation={[0, 1.134, 0]}>
        <mesh geometry={nodes.Box372_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[-136.584, -47.366, 136.927]} rotation={[0, 1.134, 0]}>
        <mesh geometry={nodes.Box373_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-135.871, -94.488, 137.729]} rotation={[0, 1.134, 0]}>
        <mesh geometry={nodes.Box374_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[1.625, 61.391, 123.127]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box375_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[1.634, -77.03, 249.552]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box376_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[1.634, -148.827, 78.672]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box377_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[0.649, -16.498, 78.246]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box378_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.586, -26.49, 78.255]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box379_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.586, -69.526, 78.255]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box380_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.649, -58.389, 78.246]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box381_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.586, -47.239, 78.255]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box382_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.649, -80.563, 78.246]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box383_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.586, -90.555, 78.255]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box384_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.649, -122.847, 78.246]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box385_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.586, -112.842, 78.255]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box386_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.649, -101.705, 78.246]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box387_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.649, -37.247, 78.246]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box388_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[-57.684, -148.827, 57.944]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Box389_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.111, 55.395, -49.281]} />
      </group>
      <group position={[0.526, -41.045, 249.26]} rotation={[-Math.PI, 0.14, -Math.PI]}>
        <mesh geometry={nodes.Box390_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.526, -29.909, 249.197]} rotation={[-Math.PI, 0.14, -Math.PI]}>
        <mesh geometry={nodes.Box391_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.526, -51.051, 249.197]} rotation={[-Math.PI, 0.14, -Math.PI]}>
        <mesh geometry={nodes.Box392_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.526, -8.766, 249.197]} rotation={[-Math.PI, 0.14, -Math.PI]}>
        <mesh geometry={nodes.Box393_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.802, -6.312, 245.43]} rotation={[1.571, -0.015, -1.571]}>
        <mesh geometry={nodes.Box394_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.66, 19.841, -48.296]} />
      </group>
      <group position={[0.526, -18.758, 249.26]} rotation={[-Math.PI, 0.14, -Math.PI]}>
        <mesh geometry={nodes.Box395_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.649, 125.075, 122.703]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box396_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[1.625, 147.965, 99.579]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box397_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[73.11, 55.793, -49.272]} />
      </group>
      <group position={[0.649, 103.651, 122.703]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box398_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.649, 82.509, 122.703]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box399_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.586, 113.939, 122.711]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box400_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.586, 92.515, 122.711]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box401_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.586, 179.088, 99.163]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box402_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[30.056, 19.41, -48.233]} />
      </group>
      <group position={[0.649, 190.225, 99.155]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box403_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.649, 169.083, 99.155]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Box404_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[21.697, 25.607, -48.296]} />
      </group>
      <group position={[0.481, 130.2, -0.011]} rotation={[1.549, -0.785, 3.126]}>
        <mesh geometry={nodes.Box405_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-71.783, 19.267, -134.741]} />
      </group>
      <group position={[0.481, 130.2, -0.011]} rotation={[Math.PI / 4, 0.016, 1.571]}>
        <mesh geometry={nodes.Box406_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-71.783, 19.267, -134.741]} />
      </group>
      <group position={[-121.476, 130.493, 0.781]} rotation={[1.593, 0.785, -0.016]}>
        <mesh geometry={nodes.Box407_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.246, 19.84, -48.296]} />
      </group>
      <group position={[0.481, 130.2, -0.011]} rotation={[2.356, -0.016, -1.571]}>
        <mesh geometry={nodes.Box408_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-71.783, 19.267, -134.741]} />
      </group>
      <group position={[-0.054, 195.903, -0.011]} rotation={[0, -0.159, Math.PI / 2]}>
        <mesh geometry={nodes.Box409_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.246, 117.532, -31.84]} />
      </group>
      <group position={[-0.054, 195.903, -0.011]} rotation={[0, 1.412, Math.PI / 2]}>
        <mesh geometry={nodes.Box410_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.246, 117.532, -31.84]} />
      </group>
      <group position={[-0.054, 195.903, -0.011]} rotation={[Math.PI, 0.159, -Math.PI / 2]}>
        <mesh geometry={nodes.Box411_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.246, 117.532, -31.84]} />
      </group>
      <group position={[-0.054, 195.903, -0.011]} rotation={[-Math.PI, -1.412, -Math.PI / 2]}>
        <mesh geometry={nodes.Box412_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[14.246, 117.532, -31.84]} />
      </group>
      <group position={[-0.054, 37.338, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cylinder02_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[0, 0, -29.49]} />
      </group>
      <group position={[204.894, 166.666, -0.031]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes['Cylinder136_Material_#19_0'].geometry} material={materials.Material_19} position={[0, 0, -66.221]} />
      </group>
      <group position={[-0.032, 166.665, -204.894]} rotation={[-Math.PI / 2, 0, -1.571]}>
        <mesh geometry={nodes['Cylinder148_Material_#19_0'].geometry} material={materials.Material_19} position={[0, 0, -66.221]} />
      </group>
      <group position={[-204.894, 166.665, 0.032]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Cylinder154_Material_#19_0'].geometry} material={materials.Material_19} position={[0, 0, -66.221]} />
      </group>
      <group position={[0.031, 166.665, 204.894]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes['Cylinder160_Material_#19_0'].geometry} material={materials.Material_19} position={[0, 0, -66.221]} />
      </group>
      <group position={[-0.054, 185.857, -0.011]} scale={[0.95, 1, 0.95]}>
        <mesh geometry={nodes.Line020_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[19.03, -3.046, 0]} />
      </group>
      <group position={[97.099, 27.997, 97.743]} rotation={[-1.183, 0.361, -0.857]}>
        <mesh geometry={nodes.Sphere020_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[12.033, 4.958, -45.999]} />
      </group>
      <mesh geometry={nodes.Cylinder03_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[-0.037, 365.253, 0.078]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder128_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[0, 699.649, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Cylinder134_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[204.724, 89.871, -0.164]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Cylinder135_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[204.885, 58.616, -0.099]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder137_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[204.861, 38.452, -0.099]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder138_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[45.745, 35.451, -0.099]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.Cylinder146_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[32.394, 35.451, 32.311]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.Cylinder147_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[32.311, 35.451, -32.394]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.Cylinder149_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-0.164, 89.871, -204.724]} rotation={[-Math.PI / 2, 0, -1.571]} />
      <mesh geometry={nodes.Cylinder150_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-0.1, 38.452, -204.861]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder151_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[-0.1, 58.616, -204.886]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder152_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-0.1, 35.451, -45.745]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Cylinder153_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-32.394, 35.451, -32.311]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
      <mesh geometry={nodes.Cylinder155_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-204.724, 89.871, 0.164]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder156_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-204.861, 38.452, 0.099]} rotation={[-Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Cylinder157_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[-204.886, 58.616, 0.099]} rotation={[-Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Cylinder158_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-45.745, 35.451, 0.1]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.Cylinder159_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-32.311, 35.451, 32.394]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.Cylinder161_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[0.164, 89.871, 204.725]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder162_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[0.1, 38.452, 204.861]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder163_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[0.1, 58.616, 204.886]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder164_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[0.1, 35.451, 45.745]} />
      <mesh geometry={nodes.GeoSphere067_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[88.146, 193.781, 81.778]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.GeoSphere068_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[81.779, 193.781, -88.146]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.GeoSphere069_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[-88.146, 193.781, -81.778]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.GeoSphere070_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[-81.779, 193.781, 88.146]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
      <mesh geometry={nodes.Line015_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[89.129, 133.954, -15.18]} />
      <mesh geometry={nodes.Line018_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[119.442, 77.928, 113.075]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.Line022_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[113.075, 77.928, -119.442]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.Line023_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-15.18, 133.954, -89.13]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.Line024_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-119.442, 77.928, -113.075]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.Line025_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-89.129, 133.954, 15.18]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Line026_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-113.075, 77.928, 119.442]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
      <mesh geometry={nodes.Line027_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[15.18, 133.954, 89.129]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.Shape007_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[119.442, 77.928, 113.075]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.Shape008_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[113.075, 77.928, -119.442]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.Shape009_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-119.442, 77.928, -113.075]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.Shape010_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-113.075, 77.928, 119.442]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
      <mesh geometry={nodes.Sphere02_Glass_Crystal_Clear_Simple_0.geometry} material={materials.Glass_Crystal_Clear_Simple} position={[0.021, -57.18, 0.016]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sphere022_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[171.199, 0.218, -0.241]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sphere023_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[76.735, 170.758, -0.241]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sphere024_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[85.343, -17.856, -91.71]} rotation={[-1.958, 0.361, 0.857]} />
      <mesh geometry={nodes.Sphere025_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-0.241, 0.218, -171.199]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Sphere026_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-0.241, 170.758, -76.735]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Sphere027_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-91.71, -17.856, -85.343]} rotation={[-1.958, -0.361, 2.285]} />
      <mesh geometry={nodes.Sphere028_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-171.199, 0.218, 0.241]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Sphere029_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-76.735, 170.758, 0.241]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Sphere03_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[0.006, -90.739, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sphere030_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[-85.343, -17.856, 91.71]} rotation={[-1.183, -0.361, -2.285]} />
      <mesh geometry={nodes.Sphere031_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[0.241, 0.218, 171.199]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Sphere032_Metal_Gold_Karat_0.geometry} material={materials.Metal_Gold_Karat} position={[0.241, 170.758, 76.735]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
    </>
  )
}
export default Chandelier;
useGLTF.preload('/resources/chandelier.glb')
