/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 desk_bank_teller.glb 
Author: abdillaamy (https://sketchfab.com/abdillaamy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desk-bank-teller-a5c7f6dfcea747c38f59ba7746d06209
Title: Desk (Bank Teller)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Counter(props) {
  const { nodes, materials } = useGLTF('/resources/desk_bank_teller.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeskDraw_1_DrawerUV_0.geometry} material={materials.DrawerUV} />
      <mesh geometry={nodes.DeskDraw_1_HandleTexture_0.geometry} material={materials.HandleTexture} />
      <mesh geometry={nodes.TellerDesk_DeskWood_0.geometry} material={materials.DeskWood} />
      <mesh geometry={nodes.DeskDraw_2_DrawerUV_0.geometry} material={materials.DrawerUV} />
      <mesh geometry={nodes.DeskDraw_2_HandleTexture_0.geometry} material={materials.HandleTexture} />
      <mesh geometry={nodes.DeskDraw_3_DrawerUV_0.geometry} material={materials.DrawerUV} />
      <mesh geometry={nodes.DeskDraw_3_HandleTexture_0.geometry} material={materials.HandleTexture} />
    </group>
  )
}
export default Counter;

useGLTF.preload('/resources/desk_bank_teller.glb')
