/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bank_teller_cubical.glb 
Author: abdillaamy (https://sketchfab.com/abdillaamy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bank-teller-cubical-237f5748963644779985f550257fd8a6
Title: Bank Teller Cubical
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Counter2(props) {
  const { nodes, materials } = useGLTF('/resources/bank_teller_cubical.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={1.832}>
        <mesh geometry={nodes.CubicalBase_Stone_texture_0.geometry} material={materials.Stone_texture} />
        <mesh geometry={nodes.CubicalBase_Wood_0.geometry} material={materials.Wood} />
        <mesh geometry={nodes.CubicalBase_BronzeTexture_0.geometry} material={materials.BronzeTexture} />
        <mesh geometry={nodes.Glass_5_WindowGlass_0.geometry} material={materials.WindowGlass} position={[9.522, 10.279, 7.141]} scale={[8.235, 6.039, 0.061]} />
        <mesh geometry={nodes.Glass_4_WindowGlass_0.geometry} material={materials.WindowGlass} position={[18.921, 10.261, 7.141]} scale={[8.235, 6.039, 0.061]} />
        <mesh geometry={nodes.Glass_3_WindowGlass_0.geometry} material={materials.WindowGlass} position={[9.54, 10.261, 7.141]} scale={[8.235, 6.039, 0.061]} />
        <mesh geometry={nodes.Glass_2_WindowGlass_0.geometry} material={materials.WindowGlass} position={[18.42, 10.261, 7.141]} scale={[8.235, 6.039, 0.061]} />
      </group>
    </group>
  )
}

export default Counter2;
useGLTF.preload('/resources/bank_teller_cubical.glb')
