/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 frames1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Frames1(props) {
  const { nodes, materials } = useGLTF('/resources/frames1.glb')
  return (
    <>
    <pointLight
      args={['gold', 30,5,1]}
      position={[7.5, 6, -5]}
      rotation-x={Math.PI/2}
    />
    <group {...props} dispose={null}>
      <group position={[6.406, 1.754, 0.04]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.PHOTO} />
      </group>
      <group position={[2.729, 2.167, 0.039]}>
        <mesh geometry={nodes.Object_7.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.PHOTO2} />
      </group>
      <group position={[5.349, 2.951, 0.03]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.PHOTO3} />
      </group>
      <group position={[2.606, 0.77, 0.036]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.PHOTO4} />
      </group>
      <group position={[3.913, 0.493, 0.05]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.PHOTO5} />
      </group>
      <group position={[5.116, 1.749, 0.022]}>
        <mesh geometry={nodes.Object_19.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.PHOTO6} />
      </group>
      <group position={[3.853, 1.652, 0.02]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.PHOTO7} />
      </group>
      <group position={[2.839, 3.332, 0.033]}>
        <mesh geometry={nodes.Object_25.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.PHOTO8} />
      </group>
      <group position={[5.222, 0.57, 0.025]}>
        <mesh geometry={nodes.Object_28.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.PHOTO9} />
      </group>
      <group position={[4.063, 2.976, 0.039]}>
        <mesh geometry={nodes.Object_31.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.FRAME} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.PHOTO10} />
      </group>
    </group>
    </>
  )
}
export default Frames1
useGLTF.preload('/resources/frames1.glb')
