/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gramophone.glb 
Author: Loïc (https://sketchfab.com/loichuet1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gramophone-2458f980cf584c45a130df3fc39d47ff
Title: Gramophone
*/

import React, { useRef,useEffect,useState,useContext } from 'react'
import { useGLTF,Outlines } from '@react-three/drei'
import { GlobalContext } from '../../App'

export function Gramophone(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/resources/gramophone.glb')
  const [isOutlined, setIsOutlined] = useState(false)
  const {zoomed, proximity}= useContext(GlobalContext)
  
  useEffect(() => {
    // const near=props.isNear
    
    if(proximity==="music" && zoomed===false){
      setIsOutlined(true);
    }
    else if(proximity==="music" && zoomed===true){
      setIsOutlined(false)
    }
    else{
      setIsOutlined(false)
    }
  });

  return (
    <>
    <pointLight
      args={['white', 1,1,1]}
      position={[-6.1,3,-3.7]}
      rotation-x={Math.PI/2}
    />
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} rotation={[Math.PI / 2, 0, 0]}>
        {isOutlined  &&<Outlines angle={0} thickness={0.05} color="yellow" />}
        </mesh>
      </group>
    </group>
    </>
  )
}
export default Gramophone
useGLTF.preload('/resources/gramophone.glb')
