/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 banker_lamp.glb 
Author: michael.jelicic (https://sketchfab.com/michael.jelicic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/banker-lamp-a71cefed7c0a4be09cfbb0c103a7b297
Title: Banker Lamp
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lamp(props) {
  const { nodes, materials } = useGLTF('/resources/banker_lamp.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.002, 5.568, 0.004]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[0.051, 0, 0.311]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Lamp_greenGlass_0.geometry} material={materials.greenGlass} />
            <mesh geometry={nodes.Lamp_whiteGLass_0.geometry} material={materials.whiteGLass} />
          </group>
          <group position={[0.049, -0.106, 0.408]} scale={1.693}>
            <mesh geometry={nodes.Lever_Brass_0.geometry} material={materials.Brass} />
            <mesh geometry={nodes.Lever_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <mesh geometry={nodes.Circle_Brass_0.geometry} material={materials.Brass} />
          <mesh geometry={nodes.BulbHolder__0.geometry} material={materials.BulbHolder__0} position={[0.049, -0.106, 0.282]} scale={[0.278, 0.278, 0.017]} />
          <mesh geometry={nodes.Vert002_Brass_0.geometry} material={materials.Brass} position={[0, 0, 0.044]} />
          <mesh geometry={nodes.Vert001_Brass_0.geometry} material={materials.Brass} position={[0, 0, 0.044]} />
          <mesh geometry={nodes.Circle002_Brass_0.geometry} material={materials.Brass} position={[0.049, 0.141, 0.297]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.plastic__0.geometry} material={materials.BulbHolder__0} position={[0.049, -0.123, 0.297]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.metalBulbHolder_Material005_0.geometry} material={materials['Material.005']} position={[0.049, -0.123, 0.297]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Bulb001_Material003_0.geometry} material={materials['Material.003']} position={[0.049, 0.005, 0.297]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <mesh geometry={nodes.Plane_Material004_0.geometry} material={materials['Material.004']} position={[-0.432, 0.372, -0.669]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

export default Lamp;

useGLTF.preload('/resources/banker_lamp.glb')
