/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 table.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
  const { nodes, materials } = useGLTF('/resources/table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_66.geometry} material={materials['WoodA121212.002']} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['trimA12344.001']} rotation={[-Math.PI, -Math.PI / 4, 0.004]} scale={0.923} />
    </group>
  )
}
export default Table
useGLTF.preload('/resources/table.glb')
