/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 vault_door.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Vault_door(props) {
  const { nodes, materials } = useGLTF('/resources/vault_door.glb')
  return (
    <>
    <pointLight
      args={['white', 7,2,1]}
      position={[-1, 5, 7.6]}
      rotation-y={Math.PI/2}
    />
    <group {...props} dispose={null}>
      <group position={[-24.398, 675.913, 80.038]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} position={[-4.117, -2.114, 277.029]} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} position={[-4.117, -2.114, 277.029]} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} position={[-4.117, -2.114, 277.029]} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Scene_-_Root']} position={[-4.117, -2.114, 277.029]} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} position={[-4.117, -2.114, 277.029]} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Scene_-_Root']} position={[-4.117, -2.114, 277.029]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Scene_-_Root']} position={[-4.117, -2.114, 277.029]} />
      </group>
    </group>
    </>
  )
}
export default Vault_door;
useGLTF.preload('/resources/vault_door.glb')
